language: c

# Handle git submodules yourself
# use sed to replace the SSH URL with the public URL, then initialize submodules

git:
    submodules: false


before_install:
 - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive
 - sudo apt-get update -qq
 - sudo apt-get install -y binutils-avr gcc-avr scons python-pip arduino 
 - wget http://ftp.us.debian.org/debian/pool/main/a/arduino/arduino-core_1.0.5+dfsg2-4_all.deb
 - sudo dpkg -i arduino-core_1.0.5+dfsg2-4_all.deb
 - sudo rm -f /usr/share/arduino/libraries/Robot_Control/Wire.h
 - sudo pip install confduino
 - sudo pip install pyavrutils
 - sudo pip install path.py
 - sudo pip install nose
 - sudo pip install nose_ittr

install: 

script:  nosetests -v tests

